name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:

  android_luajit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28b
      - name: Build
        run: |
          export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
          cd build
          sudo apt-get install gcc-multilib
          ./make_android_luajit_arm64.sh  
      - name: UploadJit
        uses: actions/upload-artifact@v3
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
  
  # ohos:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install NDK
  #       run: |
  #         cd ~
  #         cd ~
  #         curl -O https://repo.huaweicloud.com/harmonyos/os/4.1-Release/ohos-sdk-windows_linux-public.tar.gz
  #         tar xvfz ohos-sdk-windows_linux-public.tar.gz
  #         cd ohos-sdk/linux
  #         unzip -o -d ./ native-linux-x64-4.1.7.5-Release.zip
  #     - name: Build
  #       run: |
  #         cd build
  #         chmod +x make_ohos_lua5*.sh
  #         OHOS_NDK_HOME=~/ohos-sdk/linux/native ./make_ohos_lua54.sh
  #         OHOS_NDK_HOME=~/ohos-sdk/linux/native ./make_ohos_lua53.sh
  #     - name: Upload
  #       uses: actions/upload-artifact@v3
  #       with:
  #         path: ./build/plugin_lua54/**/*
  #         name: plugin_lua54
  #     - name: Upload53
  #       uses: actions/upload-artifact@v3
  #       with:
  #         path: ./build/plugin_lua53/**/*
  #         name: plugin_lua53

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_linux64_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v3
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit  
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_ios_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v3
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_osx_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v3
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit  
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
    
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Luajit
        run: |
          cd build
          .\make_win64_luajit.bat
      
      - name: UploadJit
        uses: actions/upload-artifact@v3
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
          
  windows-luajit-32:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build Luajit
        run: |
          cd build
          .\make_win32_luajit.bat  
      - name: UploadJit
        uses: actions/upload-artifact@v3
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
    

   
